Support to hdf on Dxp and added QE65000
lnls-sol/py4syn pull request #11
Opened 2017-01-25 10:40 UTC by gabrielfedel

Hello, 
I added support to save hdf on mapping process for DxpClass.
I added too a class to spectrometer QE65000 (with hdf support too).

2017-01-25 17:30 UTC, hhslepicka requested changes
Hi @gabrielfedel! 
Thank you for your collaboration, nice work! :)
I made a few comments and some changes are needed before we can merge it.
Please let me know what you think about it.

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +                 imageDeep=2048):
What is this ```imageDeep```?
Is this defined once in the device and remain the same for the whole use of it?
The name is a bit confusing.

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +        imageDeep : how many points are collected each time
I would recommend to name it something more clear such as ```num_points```.

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +            r = int(channel[6])
How is this ```getValueChannel``` being used?
Why do we need to have this index 6 hardcoded? 
If it is necessary, I would recommend the use of a constant in order to make it easier to understand now and in the future.

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +        self.ch = ch
When is saveSpectrum being called?

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +        self.ch = ch
This method is a bit confusing, would you mind to show a code snippet with a use case for it?

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +    def setNormValue(self, value):
The filename + saving to txt code appears in more than one place.
Would you mind to refactor it and make it usable for all the cases without repeating the code?

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +        self.pvStart.put("Stop")
The device starts the acquisition when you write "Stop" to the Start PV?

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +    def close(self):
Isn't this the same as ```stopCount``` ?

2017-01-25 17:30 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +    def startCollectImage(self, rows=0, cols=0):
Also the same as for DXP, maybe you can create a base class and DXP, DXPFake and this device can inherit from it. This way we have the code in a more maintainable fashion and easier to fix.

2017-01-26 11:13 UTC, gabrielfedel commented on py4syn/epics/QE65000Class.py
> +        self.pvStart.put("Stop")
Yes... We are using an ioc from another author... I could change the ioc to let this better.

2017-01-26 11:16 UTC, gabrielfedel commented
Great! I will review this soon! Thanks!

2017-01-26 11:19 UTC, gabrielfedel commented on py4syn/epics/QE65000Class.py
> +    def startCollectImage(self, rows=0, cols=0):
Are you saying a base class to work with this collect image way?

2017-01-26 16:44 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +        self.pvStart.put("Stop")
No need to change the IOC, I was just curious about it! :+1:

2017-01-26 16:45 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +    def startCollectImage(self, rows=0, cols=0):
Yes! In order to keep this code that is mainly the same but in one place. A base class or move this to something that can be imported and used by all of them and future developments with the same idea.

2017-01-26 17:29 UTC, gabrielfedel commented on py4syn/epics/QE65000Class.py
> +    def startCollectImage(self, rows=0, cols=0):
great! I will do it.

2017-02-03 21:47 UTC, hhslepicka commented on py4syn/epics/QE65000Class.py
> +        if self.pvDarkCorrection.get() == 1:
@gabrielfedel, is it possible to change during runtime or it is configured at the IOC and available as read-only on this PV?
If it is possible to change during runtime I would recommend to have some sort check on the moment that you read the pvSpectrum to point to the correct value.

2017-02-07 15:53 UTC, gabrielfedel commented on py4syn/epics/DxpClass.py
> +                 imageDeep=2048):
I change to numPoints

2017-02-07 15:53 UTC, gabrielfedel commented on py4syn/epics/DxpClass.py
> +        imageDeep : how many points are collected each time
solved

2017-02-07 15:53 UTC, gabrielfedel commented on py4syn/epics/DxpClass.py
> +    def setNormValue(self, value):
Solved. I moved to ImageHDFClass

2017-02-07 15:55 UTC, gabrielfedel commented on py4syn/epics/QE65000Class.py
> +        if self.pvDarkCorrection.get() == 1:
Good idea

2017-02-08 15:27 UTC, gabrielfedel commented on py4syn/epics/QE65000Class.py
> +    def close(self):
yes, I removed it.

2017-02-08 15:39 UTC, gabrielfedel commented on py4syn/epics/DxpClass.py
> +            r = int(channel[6])
The PVs has the format mcaC.Rr (where C is channel and R is ROI). If PV is only mcaC then we call saveSpectrum, if is a mcaC.Rr, is just a point collect.

I change to a constant this values (4 and 6)

2017-02-08 15:39 UTC, gabrielfedel commented on py4syn/epics/DxpClass.py
> +        self.ch = ch
It is called on getValueChannel (when PV is a spectrum).

2017-02-08 15:40 UTC, gabrielfedel commented
I think I finished the changes, tell me if you think necessary more updates.

2017-02-08 18:54 UTC, hhslepicka requested changes

2017-02-08 18:54 UTC, hhslepicka commented on py4syn/epics/ImageHDFClass.py
> +class ImageHDF(StandardDevice, ICountable):
ImageHDF should be just a class. Your devices must be StandardDevice and ICountable.
E.g.: DxpFake(StandardDevice, ICountable, ImageHDF).
Do you agree?

2017-02-08 18:56 UTC, hhslepicka commented
Hi @gabrielfedel, thank you for the modifications. It is getting much better!
There is just this one point that I mentioned on the review. Let me know if you agree.

2017-02-08 19:04 UTC, hhslepicka commented
Also, please squash it in order to facilitate the review and history.

2017-02-09 12:26 UTC, gabrielfedel commented on py4syn/epics/ImageHDFClass.py
> +class ImageHDF(StandardDevice, ICountable):
Hello Hugo. My first try was like your suggestion, but i not found an way to start the 2 constructors (StandardDevice and ImageHDF) on subclasses... Do you know if there is an way to do this?  Or, maybe, another solution (remove from ImageHDF constructor and create a simple method)...

2017-02-09 12:30 UTC, gabrielfedel commented
Sorry, I didn't understand it "lease squash it in order to facilitate the review and history". Did I do something in a wrong order?

2017-02-09 17:31 UTC, hhslepicka commented on py4syn/epics/ImageHDFClass.py
> +class ImageHDF(StandardDevice, ICountable):
Hi Gabriel, I will take a better look at that! For now let's leave as is.

2017-02-09 17:32 UTC, hhslepicka commented
@gabrielfedel, squash is used to reduce the number of commits and make it easier to review and also check the history.
Please take a look at: http://stackoverflow.com/questions/31668794/squash-all-your-commits-in-one-before-a-pull-request-in-github

2017-02-13 10:02 UTC, gabrielfedel commented
Thank you for the reference. I will use squash next time. 
Something else to fix?

2017-02-13 17:10 UTC, hhslepicka commented
@gabrielfedel, looks good to me now.
Thank you!

2017-02-13 17:10 UTC, hhslepicka approved these changes

2017-02-13 17:10 UTC, merged

2017-02-13 17:35 UTC, gabrielfedel commented
Great!
Thank you for review!