Improve getTimes from DxpClass
lnls-sol/py4syn pull request #25
Opened 2017-05-05 18:29 UTC by gabrielfedel

Fix the getCountTime and added getRealTime, where realTime = LiveTime + DeadTime

2017-05-05 22:45 UTC, hhslepicka commented
@gabrielfedel How is this DXP being used at the beam line?
Why do you need to specify the acquire time per channel?
Isn't it being used with the MCA?

2017-05-05 22:46 UTC, hhslepicka requested changes

2017-05-05 22:46 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +        return self.pvDxpAcquireTime[0].get()
Please define a constant for ```0``` to make the code more clear.

2017-05-05 22:46 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +            return self.pvDxpRealTime[1].get()
Please define a constant for ```1``` to make the code more clear.

2017-05-09 18:19 UTC, hhslepicka commented
Hi @gabrielfedel it is still unclear why you need a set of real and acquire time per channel.
Would you please clarify? I believe that this device is a bit messy.
I can understand that it probably works at the beam line but the use seems very weird to me.

2017-05-09 19:47 UTC, gabrielfedel commented
Hi @hhslepicka , this device could control more than one detector, and it is possible to set different acquisition time for each. 
Do you think I can improve the code? Or, maybe explain better?

2017-05-09 20:36 UTC, hhslepicka commented
@gabrielfedel, for now we keep it like that and we can talk offline just so I can understand better the idea behind this device and help you with that.
Merging as is.

2017-05-09 20:36 UTC, hhslepicka approved these changes

2017-05-09 20:36 UTC, merged