DxpClass for Dxp detectors
lnls-sol/py4syn pull request #8
Opened 2016-11-18 18:38 UTC by gabrielfedel

Hello Hugo, I added a DxpClass to permit to use Dxp detectors.

2016-11-18 19:21 UTC, hhslepicka commented
Hi @gabrielfedel , thanks for your contribution.
It looks pretty good to me! 👍 
I just added a small comment between lines 119 and 131.
Let me know what you think about it.

2016-11-21 11:20 UTC, gabrielfedel commented
Hi Hugo! 

I couldn't find this comment...I need to give you access to my repository?

2016-11-21 16:06 UTC, hhslepicka requested changes

2016-11-21 16:06 UTC, hhslepicka commented on py4syn/epics/DxpClass.py
> +            if fileName[-4] == '.':
Just a small comment here:
You don't need to check for the presence of the `.` at the file name, you can just do the split directly and move forward with that.  This way you can avoid the repeated code:

```
    prefix = fileName.split('.')[0]
    while os.path.exists('%s_%s%d_%04d.mca' % (prefix, self.dxpType, ch, idx)):
        idx += 1
    fileName = '%s_%s%d_%04d.mca' % \
                                  (prefix, self.dxpType, ch, idx)
```

2016-11-21 16:06 UTC, hhslepicka commented
@gabrielfedel Sorry, I forgot to submit the request for changes.

2016-11-21 17:59 UTC, gabrielfedel commented
Great suggestion, thank you!
I did it!

2016-11-21 20:55 UTC, hhslepicka approved these changes

2016-11-21 20:55 UTC, hhslepicka commented
Looks good to me! Thank you @gabrielfedel .

2016-11-21 20:55 UTC, merged